name: "Build MacOS"

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        config: [debug, release, dist]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install premake5
        uses: ./.github/actions/install-premake5

      - name: Make version
        run: make --version

      - name: Generate make files
        run: premake5 gmake --cc=${{ matrix.compiler }}

      - name: Build
        run: make config=${{ matrix.config }}
