name: "Build Ubuntu"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        config: [debug, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install premake5
        uses: ./.github/actions/install-premake5

      - name: Generate make files
        run: premake5 gmake --cc=${{ matrix.compiler }}

      - name: Build
        run: make config=${{ matrix.config }}
