name: "Build Windows"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        visual-studio: [vs2022]
        compiler: [msc, clang]
        config: [debug, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install premake5
        uses: ./.github/actions/install-premake5

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Generate project files
        shell: bash
        run: premake5 ${{ matrix.visual-studio }} --cc=${{ matrix.compiler }}

      - name: Build
        shell: cmd
        run: msbuild hill.sln /p:Configuration=${{ matrix.config }}
