name: "Test Unit"

on: [push]

jobs:
  test-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        config: [debug, release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install premake5
        uses: ./.github/actions/install-premake5

      - name: Make version
        run: make --version

      - name: Generate make files
        run: premake5 gmake --cc=${{ matrix.compiler }}

      - name: Build
        run: make config=${{ matrix.config }}

      - name: Run tests
        run: ./bin/${{ matrix.config }}/hill test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results-${{ matrix.compiler }}-${{ matrix.config }}
          path: test-results.xml
