name: windows-msvc-2022

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  windows-msvc-2022:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          repository: premake/premake-core

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: gen projects vs2022 msc
      run: premake5 vs2022
      shell: bash

    - name: build debug
      run: msbuild hill.sln /p:Configuration=Debug
      shell: cmd
    - name: build release
      run: msbuild hill.sln /p:Configuration=Release
      shell: cmd
    - name: build dist
      run: msbuild hill.sln /p:Configuration=Dist
      shell: cmd
