name: windows-vs2022-clang

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  windows-vs2022-clang:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          repository: premake/premake-core

    - name: gen projects vs2022 clang
      run: premake5 vs2022 --cc=clang
      shell: bash

    - name: build debug
      run: msbuild hill.sln /p:Configuration=Debug
      shell: cmd
    - name: build release
      run: msbuild hill.sln /p:Configuration=Release
      shell: cmd
    - name: build dist
      run: msbuild hill.sln /p:Configuration=Dist
      shell: cmd
