name: windows-gmake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  windows-gmake:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install premake5
      uses: ./.github/actions/install-premake5
      with:
          repository: premake/premake-core

    - name: gen projects
      run: premake5 gmake --shell=posix
      shell: bash

    - name: build debug
      run: make -C hill --config=debug
      shell: bash
    - name: build release
      run: make -C hill --config=release
      shell: bash
    - name: build dist
      run: make -C hill --config=dist
      shell: bash
