name: windows-vs2022-msc

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  windows-vs2022-msc:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install premake5
      uses: ./.github/actions/install-premake5

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Generate vs2022 msc
      run: premake5 vs2022
      shell: bash

    - name: Build debug
      run: msbuild hill.sln /p:Configuration=Debug
      shell: cmd
    - name: Build release
      run: msbuild hill.sln /p:Configuration=Release
      shell: cmd
    - name: Build dist
      run: msbuild hill.sln /p:Configuration=Dist
      shell: cmd
