name: windows-gmake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  windows-gmake:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install premake5
      uses: ./.github/actions/install-premake5

    - name: Generate make files
      run: premake5 gmake --shell=posix
      shell: bash

    - name: Build debug
      run: make config=debug
      shell: bash
    - name: Build release
      run: make config=release
      shell: bash
    - name: Build dist
      run: make config=dist
      shell: bash
